# Neden NumPy

In [27]:
a = [1, 2, 3, 4]
b = [2, 3, 4, 5]

In [29]:
ab = []

for i in range(0, len(a)):
    ab.append(a[i]*b[i])

ab

[2, 6, 12, 20]

In [42]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array(b)
a*b

array([ 2,  6, 12, 20])

# Numpy Array Oluşturmak

In [47]:
import numpy as np

In [53]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [55]:
type(a)

numpy.ndarray

In [63]:
np.array([3.2, 4, 5.2, 6], dtype = "float32")

array([3.2, 4. , 5.2, 6. ], dtype=float32)

# Sıfırdan Array Oluşturma

In [72]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [80]:
np.ones((3,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [84]:
np.full((3, 5), 3, dtype = float)

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [88]:
np.arange(0, 31, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [90]:
np.linspace(0 , 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [94]:
np.random.normal(10, 4, (3, 4)) #ortalama standart sapmaya göre oluşturma

array([[ 6.13929808,  9.84651766, 15.71152989,  7.84780776],
       [ 8.72429602, 10.08812111,  3.58762769, 12.58722963],
       [ 5.38247051, 14.89189061,  7.99827297,  4.29991499]])

In [96]:
np.random.randint(0, 10, (3, 3))

array([[6, 8, 2],
       [6, 6, 3],
       [3, 3, 4]])

# Numpy Array Özellikleri

* **ndim**: boyut sayısı
* **shape**: boyut bilgisi
* **size**: toplam eleman sayısı
* **dtype**: array veri tipi

In [17]:
import numpy as np

In [23]:
np.random.randint(10, size = 10)

array([4, 3, 7, 7, 1, 1, 0, 4, 5, 1])

In [25]:
a = np.random.randint(10, size = 10)

In [27]:
a.ndim

1

In [29]:
a.shape

(10,)

In [31]:
a.size

10

In [33]:
a.dtype

dtype('int32')

In [35]:
b = np.random.randint(10, size = (3, 5))

In [37]:
b.ndim

2

In [39]:
b.size

15

In [41]:
b

array([[5, 0, 7, 8, 9],
       [1, 4, 1, 1, 5],
       [1, 7, 7, 5, 7]])

# Yeniden Şekillendirme(reshaping)

In [1]:
import numpy as np

In [9]:
a = np.arange(1,10)
a.ndim

1

In [17]:
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Array Birleştirme

In [19]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [20]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [21]:
z = np.array([7,8,9])

In [22]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
a = np.array([[1,2,3],[4,5,6]])

In [26]:
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [27]:
np.concatenate([a,a], axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

# Array Ayırma(Splitting)

In [28]:
import numpy as np

In [29]:
x = np.array([1,2,3,99,99,3,2,1])

In [31]:
a,b,c = np.split(x, [3,5])

In [32]:
print(a,b,c)

[1 2 3] [99 99] [3 2 1]


In [34]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [35]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [39]:
ust, alt = np.vsplit(m, [2])
print(ust)
print(alt)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [40]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

# Sıralama (Sorting)

In [42]:
import numpy as np

In [43]:
v = np.array([2,1,4,3,5])

In [44]:
v

array([2, 1, 4, 3, 5])

In [45]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [46]:
v

array([2, 1, 4, 3, 5])

In [48]:
v.sort()

In [49]:
v

array([1, 2, 3, 4, 5])

In [51]:
m = np.random.normal(20,5,(3,3))

In [52]:
m

array([[19.15828728, 20.7860942 , 15.88983685],
       [28.99382555, 18.41079452, 20.51975633],
       [13.18402578, 15.81500112, 24.90338399]])

In [53]:
np.sort(m, axis = 1)

array([[15.88983685, 19.15828728, 20.7860942 ],
       [18.41079452, 20.51975633, 28.99382555],
       [13.18402578, 15.81500112, 24.90338399]])

In [54]:
np.sort(m, axis = 0)

array([[13.18402578, 15.81500112, 15.88983685],
       [19.15828728, 18.41079452, 20.51975633],
       [28.99382555, 20.7860942 , 24.90338399]])

# Index ile Elamanlara Erişmek

In [57]:
import numpy as np
a = np.random.randint(10, size = 10)
a

array([0, 8, 7, 0, 9, 7, 4, 4, 5, 1])

In [58]:
a[0]

0

In [59]:
a[-1]

1

In [60]:
a[0] = 100

In [61]:
a[0]

100

In [63]:
m = np.random.randint(10, size = (3,5))
m

array([[7, 3, 3, 9, 3],
       [2, 5, 7, 8, 2],
       [8, 2, 3, 7, 7]])

In [64]:
m[0,0]

7

In [66]:
m[1,1]

5

In [67]:
m[1,4]

2

In [73]:
m[1,4] = 99

In [74]:
m[1,4]
m

array([[ 7,  3,  3,  9,  3],
       [ 2,  5,  7,  8, 99],
       [ 8,  2,  3,  7,  7]])

In [77]:
m[1,4] = 3.2

In [78]:
m

array([[7, 3, 3, 9, 3],
       [2, 5, 7, 8, 3],
       [8, 2, 3, 7, 7]])

# Slicing ile Elemanlara Erişmek(Array Alt Kümesine Erişmek)

In [79]:
import numpy as np

In [80]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [81]:
a[0:3]

array([20, 21, 22])

In [82]:
a[:3]

array([20, 21, 22])

In [85]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [87]:
a[1::3]

array([21, 24, 27])

In [89]:
m = np.random.randint(10, size = (5,5))
m

array([[7, 6, 2, 9, 6],
       [0, 8, 1, 8, 1],
       [3, 5, 3, 6, 3],
       [4, 1, 5, 5, 8],
       [1, 5, 6, 1, 3]])

In [92]:
m[:,0]

array([7, 0, 3, 4, 1])

In [93]:
m[:,1]

array([6, 8, 5, 1, 5])

In [94]:
m[0,:]

array([7, 6, 2, 9, 6])

In [95]:
m[0]

array([7, 6, 2, 9, 6])

In [96]:
m[1,:]

array([0, 8, 1, 8, 1])

In [97]:
m[:,:]

array([[7, 6, 2, 9, 6],
       [0, 8, 1, 8, 1],
       [3, 5, 3, 6, 3],
       [4, 1, 5, 5, 8],
       [1, 5, 6, 1, 3]])

In [98]:
m[0:2, 0:3]

array([[7, 6, 2],
       [0, 8, 1]])

In [99]:
m[:, 0:2]

array([[7, 6],
       [0, 8],
       [3, 5],
       [4, 1],
       [1, 5]])

In [100]:
m[1:3, 0:2]

array([[0, 8],
       [3, 5]])

# Alt Küme Üzerinde İşlem Yapmak

In [1]:
import numpy as np
a = np.random.randint(10, size = (5,5))
a

array([[7, 6, 3, 4, 7],
       [9, 1, 2, 1, 9],
       [8, 0, 9, 8, 5],
       [0, 3, 4, 1, 1],
       [0, 2, 6, 7, 5]])

In [3]:
alt_a = a[0:3, 0:2]
alt_a

array([[7, 6],
       [9, 1],
       [8, 0]])

In [5]:
alt_a[0,0] = 9999
alt_a[1,1] = 888
alt_a

array([[9999,    6],
       [   9,  888],
       [   8,    0]])

In [7]:
a

array([[9999,    6,    3,    4,    7],
       [   9,  888,    2,    1,    9],
       [   8,    0,    9,    8,    5],
       [   0,    3,    4,    1,    1],
       [   0,    2,    6,    7,    5]])

In [15]:
m = np.random.randint(10, size = (5,5))
m

array([[0, 3, 3, 7, 2],
       [9, 8, 0, 7, 9],
       [6, 0, 8, 3, 2],
       [0, 7, 1, 5, 0],
       [5, 0, 2, 3, 3]])

In [17]:
alt_b = m[0:3, 0:2].copy()
alt_b

array([[0, 3],
       [9, 8],
       [6, 0]])

In [19]:
alt_b[0,0] = 999

In [21]:
alt_b * 3

array([[2997,    9],
       [  27,   24],
       [  18,    0]])

In [23]:
m

array([[0, 3, 3, 7, 2],
       [9, 8, 0, 7, 9],
       [6, 0, 8, 3, 2],
       [0, 7, 1, 5, 0],
       [5, 0, 2, 3, 3]])

# Fancy Index ile Elemanlara Erişmek

In [30]:
import numpy as np
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [32]:
v[1]

3

In [34]:
v[3]

9

In [36]:
v[5]

15

In [38]:
[v[1], v[3], v[5]]

[3, 9, 15]

In [40]:
al_getir = [1,2,3]

In [42]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [44]:
v[al_getir]

array([3, 6, 9])

In [48]:
m = np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [50]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [52]:
m[satir, sutun]

array([1, 5])

In [54]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [56]:
m[0, [1,2]]

array([1, 2])

In [58]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

# Koşullu Eleman İşlemleri

In [61]:
import numpy as np
v = np.array([1,2,3,4,5])

In [65]:
v >3

array([False, False, False,  True,  True])

In [67]:
v[v < 3]

array([1, 2])

In [69]:
v[v>=3]

array([3, 4, 5])

In [71]:
v[v != 3]

array([1, 2, 4, 5])

In [73]:
v

array([1, 2, 3, 4, 5])

In [77]:
v * 2

array([ 2,  4,  6,  8, 10])

In [79]:
v *5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [81]:
v**2

array([ 1,  4,  9, 16, 25])

# Matemtiksel İşlemler

In [86]:
import numpy as np
v = np.array([1,2,3,4,5])

In [88]:
v -1

array([0, 1, 2, 3, 4])

In [90]:
v*5

array([ 5, 10, 15, 20, 25])

In [94]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [96]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [98]:
np.power(v,3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [100]:
np.mod(v,2)

array([1, 0, 1, 0, 1], dtype=int32)

In [102]:
np.absolute(np.array([-3]))

array([3])

In [106]:
np.sin(360)

0.9589157234143065

In [108]:
np.log2(v)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809])

In [114]:
# ?np # cheatsheet

# Numpy ile İki Bilinmeyenli Denklem Çözümü

In [2]:
import numpy as np

5 * x0 + x1 = 12

x0 + 3*x1 = 10

In [8]:
a = np.array([[5,1], [1,3]])
b = np.array([12,10])

In [10]:
a

array([[5, 1],
       [1, 3]])

In [12]:
b

array([12, 10])

In [16]:
x = np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])